---
- name: Add inventory hosts to Ansible Tower survey
  hosts: all
  gather_facts: no
  vars_files:
    - ./credentials/tower_credentials.yml

  tasks:

  - name: Print out inventory hosts
    debug:
       msg: "{{ item }}"
    with_inventory_hostnames:
    - all
    run_once: yes

  - name: Build survey_spec from template
    template:
      src: ./templates/survey.j2
      dest: survey.json
    delegate_to: localhost

  - name: Build Ansible Tower template with Survey
    tower_job_template:
        name: "CONFIGURE PORT"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Ansible General Demo Exercises"
        playbook: "build_survey"
        credential: "Demo Credential"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{playbook_dir}}/survey.json') }}"
        tower_username: "{{ TOWER_USERNAME }}"
        tower_password: "{{ TOWER_PASSWORD }}"
        tower_host: https://tower.michaelanthonyford.com
        validate_certs: no
    delegate_to: localhost
    run_once: yes
