---
- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: localhost
  gather_facts: no
  tasks:

    - name: DISPLAY THE INJECTED EXTRA VAR
      set_fact:
        key_to_auth: "{{ lookup('file', '{{ secret_key }}') }}"

    - name: Set authorized key taken from file
      authorized_key:
        user: "{{ user_name }}"
        state: present
        key: "{{ the_key }}"
      delegate_to: localhost

    - name: CLONE THE GIT REPO
      git:
        repo: "git@github.com:michaelford85/ansible-aci.git"
        dest: "/tmp/my_test_repo"
        key_file: "{{ secret_key  }}"
        accept_hostkey: yes
      delegate_to: localhost

    - name: Remove authorized key taken from file
      authorized_key:
        user: "{{ user_name }}"
        state: absent
        key: "{{ the_key }}"
      delegate_to: localhost
