---
- name: ADD SSH KEY TO IDENTITY
  hosts: localhost
  tasks:

  - name: CREATE NEW SSH KEY FILE
    file:
      dest: "~/.ssh/temp_key.pem"
      content: "{{lookup('file', '"{{ secret_key }}"')}}"

  - name: LOAD SSH KEY
    shell: |
      ssh-add ~/.ssh/temp_key.pem


- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: control
  gather_facts: no
  tasks:

    - name: CLONE THE GIT REPO
      git:
        repo: git@github.com:michaelford85/ansible-aci.git
        dest: /tmp/my_test_repo
        key_file: "{{ secret_key  }}"
        accept_hostkey: yes
