---
- name: DEMO A PRIVATE KEY IN ANSIBLE ENGINE
  hosts: localhost
  gather_facts: no
  tasks:

    - name: CLONE THE GIT REPO
      git:
        repo: git@github.com:michaelford85/ansible-aci.git
        dest: /tmp/my_test_repo
        key_file: ~/.ssh/github_michaelford85
