---
# - name: ADD SSH KEY TO IDENTITY
#   hosts: localhost
#   gather_facts: no
#   tasks:
#
#   - name: CREATE NEW SSH KEY FILE
#     copy:
#       dest: "/tmp/temp_key.pem"
#       content: "{{lookup('file', '{{ secret_key }}')}}"
#       mode: 600
#
#   - name: LOAD SSH KEY
#     shell: |
#       ssh-add /tmp/temp_key.pem


- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: control
  gather_facts: no
  tasks:

    - name: CREATE NEW SSH KEY FILE
      copy:
        dest: "/tmp/temp_key.pem"
        content: "{{lookup('file', '{{ secret_key }}')}}"

    - name: CHANGE OWNER
      file:
        path: "/tmp/temp_key.pem"
        owner: centos
      become: yes

    - name: CHANGE OWNER
      file:
        path: "/tmp/temp_key.pem"
        mode: 600

    - name: LOAD SSH KEY
      shell: |
        ssh-add /tmp/temp_key.pem

    - name: CLONE THE GIT REPO
      git:
        repo: git@github.com:michaelford85/ansible-aci.git
        dest: /tmp/my_test_repo
        key_file: "{{ secret_key  }}"
        accept_hostkey: yes
