---
- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: control
  gather_facts: no
  become: yes
  tasks:


    - name: Add SSH IDENTITY
      command: ssh-add K "{{ secret_key }}"
      delegate_to: localhost

    - name: CLONE THE GIT REPO
      git:
        repo: git@github.com:michaelford85/ansible-aci.git
        dest: /tmp/my_test_repo
        key_file: "{{ secret_key  }}"
        accept_hostkey: yes
