- name: Gather Facts
  hosts: all
  gather_facts: yes
  tasks:

    - name: Print RHEL Node hostnames
      setup:
      register: facts_output

    - name: Print facts_output
      debug:
        var: facts_output
