- name: Add Linux User
  hosts: all
  gather_facts: yes
  tasks:

    - name: Print RHEL Node hostnames
      setup:
      register: facts_output

    - name: Print facts_output
      debug:
        var: facts_output.ansible_facts.ansible_hostname

    - name: Create User Account
      user:
        createhome: true
        name: "{{ username }}"
        shell: /bin/bash
        state: absent
        password: "{{ 'password' | password_hash('sha512') }}"
       # debug:
       #   msg: "This is a managed node named {{ facts_output.ansible_facts.ansible_hostname }}."
      when: facts_output.ansible_facts.ansible_hostname is search("node")
      become: yes
