#NOTE: This Playbook assumes use of the RHEL Linklight topology
- name: Add Linux User
  hosts: all
  gather_facts: yes
  tasks:

    - name: Print RHEL Node hostnames
      setup:
      register: facts_output

    - name: Print facts_output
      debug:
        var: facts_output.ansible_facts.ansible_hostname

    - name: Create User Account
      user:
        createhome: true
        name: "{{ username }}"
        shell: /bin/bash
        state: present
        password: "{{ password | password_hash('sha512') }}"
      when: facts_output.ansible_facts.ansible_hostname is search("node")
      become: yes

    - name: Configure sshd and sudoers
      lineinfile:
        dest: /etc/sudoers
        regexp: '^{{ username }}'
        line: '{{ username }} ALL=(ALL) PASSWD: ALL'
        state: present
        validate: visudo -cf %s
        backup: false
      notify: restart ssh
      become: yes

  handlers:

    - name: restart ssh
      service:
        name: sshd
        state: restarted
      become: yes
