#NOTE: This Playbook assumes use of the RHEL Linklight topology
- name: Run sudo Linux command
  hosts: all
  gather_facts: yes
  tasks:

    - name: Gather RHEL node facts
      setup:
      register: facts_output
      ignore_errors: yes

    - name: Print facts_output
      debug:
        var: facts_output.ansible_facts.ansible_hostname
      when: facts_output.ansible_facts.ansible_hostname is search("node")

    - name: sudo whoami
      shell: whoami
      when: facts_output.ansible_facts.ansible_hostname is search("node")
      become: yes
      register: whoami_output

    - name: Print whoami output
      debug:
        var: whoami_output.stdout
      when: facts_output.ansible_facts.ansible_hostname is search("node")
